session_name: dev
windows:
  - window_name: notes
    layout: tiled
    panes:
      - cd ~/sean && v
  - window_name: home-ops
    layout: tiled
    panes:
      - cd ~/home-ops && v
  - window_name: k9s
    layout: tiled
    panes:
      - k9s
