return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "shellcheck",
      "shfmt",
      "flake8",
      "ansible-language-server",
      "bash-language-server",
      "css-lsp",
      "eslint-lsp",
      "html-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "pylint",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "terraform-ls",
    },
  },
}
