# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
background = "#323232"
text = "#a9b7c6"

[colors.primary]
background = "#2b2b2b"
foreground = "#a9b7c6"

[colors.bright]
black = "#606366"
green = "#6a8759"
yellow = "#bbb529"
cyan = "#629755"
magenta = "#cc7832"
white = "#ffffff"
blue = "#9876aa"
red = "#4eade5"

[colors.cursor]
cursor = "#a9b7c6"
text = "#2b2b2b"

[colors.normal]
black = "#2b2b2b"
green = "#6a8759"
yellow = "#bbb529"
cyan = "#629755"
magenta = "#cc7832"
white = "#a9b7c6"
blue = "#9876aa"
red = "#4eade5"
