# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
text = "#282828"
cursor = "#d5c4a1"

[colors.bright]
white = "#fbf1c7"
yellow = "#fabd2f"
black = "#665c54"
magenta = "#d3869b"
cyan = "#8ec07c"
green = "#b8bb26"
blue = "#83a598"
red = "#fb4934"

[colors.primary]
background = "#292418"
foreground = "#d5c4a1"

[colors.normal]
white = "#d5c4a1"
yellow = "#fabd2f"
black = "#282828"
magenta = "#d3869b"
cyan = "#8ec07c"
green = "#b8bb26"
blue = "#83a598"
red = "#fb4934"

[colors.selection]
text = "#292418"
background = "#504945"
