# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#ffffff"
background = "#1a2332"

[colors.bright]
red = "#ff3e3e"
white = "#5c6370"
green = "#c5f467"
black = "#3e4452"
yellow = "#ffaf00"
magenta = "#c16cfa"
cyan = "#5cecc6"
blue = "#5cb2ff"

[colors.selection]
text = "#5c6370"
background = "#3e4452"

[colors.normal]
red = "#ff8484"
white = "#ffffff"
green = "#c5f467"
black = "#1a2332"
yellow = "#ffcc5c"
magenta = "#c16cfa"
cyan = "#5cecc6"
blue = "#5cb2ff"

[colors.cursor]
cursor = "#5cb2ff"
text = "#1a2332"
