# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.bright]
magenta = "#938aa9"
yellow = "#e6c384"
cyan = "#7aa89f"
white = "#c5c9c5"
blue = "#7fb4ca"
green = "#87a987"
red = "#e46876"
black = "#a6a69c"

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.cursor]
cursor = "#c5c9c5"
text = "#181616"

[colors.selection]
text = "#c5c9c5"
background = "#223249"

[colors.normal]
magenta = "#a292a3"
yellow = "#c4b28a"
cyan = "#8ea4a2"
white = "#c8c093"
blue = "#8ba4b0"
green = "#8a9a7b"
red = "#c4746e"
black = "#0d0c0c"
