# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
background = "#3d3d5e"
text = "#c7fb6d"

[colors.bright]
black = "#444a73"
cyan = "#b2ebff"
white = "#c8d3f5"
blue = "#9ab8ff"
green = "#c7fb6d"
magenta = "#caabff"
red = "#ff8d94"
yellow = "#ffd8ab"

[colors.normal]
black = "#1b1d2b"
cyan = "#86e1fc"
white = "#828bb8"
blue = "#82aaff"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
yellow = "#ffc777"

[colors.primary]
background = "#1f1f28"
foreground = "#dcd7ba"

[colors.cursor]
text = "#1f1f28"
cursor = "#dcd7ba"
