# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.cursor]
text = "#080808"
cursor = "#9e9e9e"

[colors.primary]
background = "#080808"
foreground = "#c6c6c6"

[colors.bright]
red = "#ff5189"
magenta = "#ae81ff"
yellow = "#c6c684"
cyan = "#85dc85"
white = "#e4e4e4"
blue = "#74b2ff"
green = "#36c692"
black = "#949494"

[colors.normal]
red = "#ff5454"
magenta = "#cf87e8"
yellow = "#e3c78a"
cyan = "#79dac8"
white = "#c6c6c6"
blue = "#80a0ff"
green = "#8cc85f"
black = "#323437"

[colors.selection]
background = "#323437"
text = "#c6c6c6"
