# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
blue = "#82aaff"
cyan = "#86e1fc"
yellow = "#ffc777"
black = "#1b1d2b"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#828bb8"

[colors.selection]
background = "#1b1f26"
text = "#828bb8"

[colors.primary]
background = "#242933"
foreground = "#c0c8d8"

[colors.bright]
blue = "#9ab8ff"
cyan = "#b2ebff"
yellow = "#ffd8ab"
black = "#444a73"
green = "#c7fb6d"
magenta = "#caabff"
red = "#ff8d94"
white = "#c8d3f5"

[colors.cursor]
cursor = "#c0c8d8"
text = "#191d24"
