# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
magenta = "#3c3228"
yellow = "#b08b74"
green = "#c6a78d"
white = "#c6a78d"
blue = "#f7e5c5"
cyan = "#e0c8a9"
black = "#2a211c"
red = "#5e4a3d"

[colors.primary]
foreground = "#c6a78d"
background = "#000000"

[colors.selection]
background = "#5e4a3d"
text = "#c6a78d"

[colors.cursor]
cursor = "#c6a78d"
text = "#2a211c"

[colors.bright]
magenta = "#3c3228"
yellow = "#b08b74"
green = "#c6a78d"
white = "#f7e5c5"
blue = "#f7e5c5"
cyan = "#e0c8a9"
black = "#856854"
red = "#5e4a3d"
